#!/bin/bash

if [ "$(ls --help | grep group-directories-first)" == "" ]; then
	alias ls='ls --color=auto --time-style=long-iso -N'
else
	# If --group-directories-first is supported, add it to ls command.
	alias ls='ls --color=auto --group-directories-first --time-style=long-iso -N'
fi

alias ll='ls -lh'
alias la='ls -lah'
alias l.='ls -dh .*'
alias ll.='ls -ldh .*'
alias df='df -Th'

# Aliases for dates.
#alias dateiso='date +%Y-%m-%dT%H:%M:%S.%N | cut -b 1-23'
alias isodate='date +%FT%T%:z'
# Date alias to use to create file names, e.g.: my-backup-$(DATE)
alias DATE='date +%Y%m%dT%H%M%S'
alias DATEZ='date +%Y%m%dT%H%M%S%z'

# less with -F (exit if text fits one screen) and -X (no clear screen after running).
alias less='less -FX --tabs=4'
# 'less' alias with more information.
alias L='less --tabs=4 -NR -P "?f%f:<stdin>.?m (%i/%m). [%s bytes] %lt/%L (%pB \%) ?x-> ?x%x"'
alias Ln='less --tabs=4 -R -P "?f%f:<stdin>.?m (%i/%m). [%s bytes] %lt/%L (%pB \%) ?x-> ?x%x"'
alias lerr='less --tabs=4 -R'
alias lessf='less +F' # less watching mode (similar to tail -f).

# Alias for 'time' (not builtin)
#alias xtime="/usr/bin/time -f 'Time: %E\nSyst: %S\nUser: %U'"

# Alias de sl... ¡prueba!
alias sl='sl -e'

# Show columns in mount command.
alias cmount='mount | column -t'

# Path command shows the paths in lines.
alias show-paths='echo -e ${PATH//:/\\n}'

# Weather & Moon
alias weather='curl wttr.in/Leon,Spain?m'
alias olweather='curl "wttr.in/Leon,Spain?m&format=3"'
alias moon-phase='curl wttr.in/Moon'

alias hexdump='hexdump -C'

