#!/bin/bash

# BASH history control:
# History size (by BASH session): 50000 commands.
HISTSIZE=50000

# Size of file where history is saved (in lines).
HISTFILESIZE=50000

# Control: ignoreboth (includes 'ignorespace' —do not save commands
# starting by space— and 'ignoredups' —do not save duplicates—).
HISTCONTROL=ignoreboth

# Timestamps in ISO format.
HISTTIMEFORMAT='%F %T '

# Editors.
export EDITOR=vim
export SVN_EDITOR=vim

# .bin directory.
if [ -d ~/.bin ]; then
	export PATH=$PATH:~/.bin
elif [ -d ~/bin ]; then
	export PATH=$PATH:~/bin
fi

