#!/bin/bash

# BASH history control:
# History size (by BASH session): save ALL commands.
HISTSIZE=

# Size of file where history is saved (in lines).
# With no value or values less than 0 no trucation is done.
HISTFILESIZE=

# Control: ignoreboth (includes 'ignorespace' —do not save commands
# starting by space— and 'ignoredups' —do not save duplicates—).
HISTCONTROL=ignoreboth

# Timestamps in ISO format.
HISTTIMEFORMAT='%F %T '

# Editors.
export EDITOR=vim
export SVN_EDITOR=vim

