#!/bin/bash

# BASH colors and prompt.
# Documentation: https://wiki.archlinux.org/index.php/Color_Bash_Prompt

# Regular colors
black='\[\033[0;30m\]'
red='\[\033[0;31m\]'
green='\[\033[0;32m\]'
yellow='\[\033[0;33m\]'
blue='\[\033[0;34m\]'
purple='\[\033[0;35m\]'
cyan='\[\033[0;36m\]'
white='\[\033[0;37m\]'

# Bold colors
b_black='\[\033[1;30m\]'
b_red='\[\033[1;31m\]'
b_green='\[\033[1;32m\]'
b_yellow='\[\033[1;33m\]'
b_blue='\[\033[1;34m\]'
b_purple='\[\033[1;35m\]'
b_cyan='\[\033[1;36m\]'
b_white='\[\033[1;37m\]'

# Underline colors
u_black='\[\033[4;30m\]'
u_red='\[\033[4;31m\]'
u_green='\[\033[4;32m\]'
u_yellow='\[\033[4;33m\]'
u_blue='\[\033[4;34m\]'
u_purple='\[\033[4;35m\]'
u_cyan='\[\033[4;36m\]'
u_white='\[\033[4;37m\]'

# Background colors
bg_black='\[\033[40m\]'
bg_red='\[\033[41m\]'
bg_green='\[\033[42m\]'
bg_yellow='\[\033[43m\]'
bg_blue='\[\033[44m\]'
bg_purple='\[\033[45m\]'
bg_cyan='\[\033[46m\]'
bg_white='\[\033[47m\]'

# High Intensity
i_black='\[\033[0;90m\]'
i_red='\[\033[0;91m\]'
i_green='\[\033[0;92m\]'
i_yellow='\[\033[0;93m\]'
i_blue='\[\033[0;94m\]'
i_purple='\[\033[0;95m\]'
i_cyan='\[\033[0;96m\]'
i_white='\[\033[0;97m\]'

# Bold High Intensity
bi_black='\[\033[1;90m\]'
bi_red='\[\033[1;91m\]'
bi_green='\[\033[1;92m\]'
bi_yellow='\[\033[1;93m\]'
bi_blue='\[\033[1;94m\]'
bi_purple='\[\033[1;95m\]'
bi_cyan='\[\033[1;96m\]'
bi_white='\[\033[1;97m\]'

# Underline and high intensity colors
ui_black='\[\033[4;90m\]'
ui_red='\[\033[4;91m\]'
ui_green='\[\033[4;92m\]'
ui_yellow='\[\033[4;93m\]'
ui_blue='\[\033[4;94m\]'
ui_purple='\[\033[4;95m\]'
ui_cyan='\[\033[4;96m\]'
ui_white='\[\033[4;97m\]'

# High Intensity backgrounds
bgi_black='\[\033[0;100m\]'
bgi_red='\[\033[0;101m\]'
bgi_green='\[\033[0;102m\]'
bgi_yellow='\[\033[0;103m\]'
bgi_blue='\[\033[0;104m\]'
bgi_purple='\[\033[0;105m\]'
bgi_cyan='\[\033[0;106m\]'
bgi_white='\[\033[0;107m\]'

reset='\[\033[0m\]'

# This function changes user color depending on which user
# you are (red if you are root, blue in any other case).
function user_color() {
	if [ $(id -u) == 0 ]; then
		echo $i_white$bg_red
	else
		echo $i_blue
	fi
}

# Depending on a environment variable, this function adds
# a return or not. Put it in the place you want of PS1.
function multiline_prompt() {
	echo -n ""
}

# Enable __git_ps1 to use a colored prompt (as of version 1.8.1).
export GIT_PS1_SHOWCOLORHINTS=true

#PS1="\[\[\033]0;\u@\h: \w\a${debian_chroot:+($debian_chroot)}\u@\h:\w:\$ "

if [ $(type -t __git_ps1) ]; then
	PS1="${debian_chroot:+($debian_chroot)}$(user_color)\u$i_yellow@$i_green\H$white:$i_cyan\w$white:\$(__git_ps1 ' [git: $i_purple%s$white] ')\$ $reset"
else
	PS1="${debian_chroot:+($debian_chroot)}$(user_color)\u$i_yellow@$i_green\H$white:$i_cyan\w$white:\$ $reset"
fi

export PS1

