#!/bin/bash

# BASH colors and prompt.
# Documentation: https://wiki.archlinux.org/index.php/Color_Bash_Prompt

# Regular colors
black='\e[0;30m'
red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
blue='\e[0;34m'
purple='\e[0;35m'
cyan='\e[0;36m'
white='\e[0;37m'

# Bold colors
b_black='\e[1;30m'
b_red='\e[1;31m'
b_green='\e[1;32m'
b_yellow='\e[1;33m'
b_blue='\e[1;34m'
b_purple='\e[1;35m'
b_cyan='\e[1;36m'
b_white='\e[1;37m'

# Underline colors
u_black='\e[4;30m'
u_red='\e[4;31m'
u_green='\e[4;32m'
u_yellow='\e[4;33m'
u_blue='\e[4;34m'
u_purple='\e[4;35m'
u_cyan='\e[4;36m'
u_white='\e[4;37m'

# Background colors
bg_black='\e[40m'
bg_red='\e[41m'
bg_green='\e[42m'
bg_yellow='\e[43m'
bg_blue='\e[44m'
bg_purple='\e[45m'
bg_cyan='\e[46m'
bg_white='\e[47m'

# High Intensity
i_black='\e[0;90m'
i_red='\e[0;91m'
i_green='\e[0;92m'
i_yellow='\e[0;93m'
i_blue='\e[0;94m'
i_purple='\e[0;95m'
i_cyan='\e[0;96m'
i_white='\e[0;97m'

# Bold High Intensity
bi_black='\e[1;90m'
bi_red='\e[1;91m'
bi_green='\e[1;92m'
bi_yellow='\e[1;93m'
bi_blue='\e[1;94m'
bi_purple='\e[1;95m'
bi_cyan='\e[1;96m'
bi_white='\e[1;97m'

# Underline and high intensity colors
ui_black='\e[4;90m'
ui_red='\e[4;91m'
ui_green='\e[4;92m'
ui_yellow='\e[4;93m'
ui_blue='\e[4;94m'
ui_purple='\e[4;95m'
ui_cyan='\e[4;96m'
ui_white='\e[4;97m'

# High Intensity backgrounds
bgi_black='\e[0;100m'
bgi_red='\e[0;101m'
bgi_green='\e[0;102m'
bgi_yellow='\e[0;103m'
bgi_blue='\e[0;104m'
bgi_purple='\e[0;105m'
bgi_cyan='\e[0;106m'
bgi_white='\e[0;107m'

reset='\e[0m'

# This function changes user color depending on which user
# you are (red if you are root, blue in any other case).
function user_color() {
	if [ $(id -u) == 0 ]; then
		echo $i_white$bg_red
	else
		echo $i_blue
	fi
}

# Depending on a environment variable, this function adds
# a return or not. Put it in the place you want of PS1.
function multiline_prompt() {
	echo -n ""
}

# Enable __git_ps1 to use a colored prompt (as of version 1.8.1).
export GIT_PS1_SHOWCOLORHINTS=true

#PS1="\[\e]0;\u@\h: \w\a${debian_chroot:+($debian_chroot)}\u@\h:\w:\$ "

if [ $(type -t __git_ps1) ]; then
	PS1="${debian_chroot:+($debian_chroot)}$(user_color)\u$i_yellow@$i_green\H$white:$i_cyan\w$white:\$(__git_ps1 ' [git: $i_purple%s$white] ')\$ $reset"
else
	PS1="${debian_chroot:+($debian_chroot)}$(user_color)\u$i_yellow@$i_green\H$white:$i_cyan\w$white:\$ $reset"
fi

export PS1

