#!/bin/bash

# Function to trim (remove leading and trailing spaces) a string.
function trim() {
	sed -e 's/^ *//' -e 's/ *$//'
}

# Function to trim left (remove leading spaces) a string.
function trim-left() {
	sed -e 's/^ *//'
}

# Function to trim right (remove trailing spaces) a string.
function trim-right() {
	sed -e 's/ *$//'
}

# From: http://www.cyberciti.biz/faq/linux-unix-colored-man-pages-with-less-command/
function cman() {
    env \
	LESS_TERMCAP_mb=$'\e[1;31m' \
	LESS_TERMCAP_md=$'\e[1;31m' \
	LESS_TERMCAP_me=$'\e[0m' \
	LESS_TERMCAP_se=$'\e[0m' \
	LESS_TERMCAP_so=$'\e[1;44;33m' \
	LESS_TERMCAP_ue=$'\e[0m' \
	LESS_TERMCAP_us=$'\e[1;32m' \
	man "$@"
}

